### ISSUE TITLE
Slider doesn't seem to work out of the box

### ISSUE THREAD

**Issue by hchiam** [phuoc-ng/csslayout#107]
I like this project! I got a working demo for tooltip: https://codepen.io/hchiam/pen/VwYXgWP?editors=1100

But slider is not working for me out of the box: https://codepen.io/hchiam/pen/YzPaBYQ?editors=1100

Anything I'm doing wrong?

**Comment by phuoc-ng** [comment]
At the moment, it seems that CodePen treats the circle as the children of the left side, and the right side as the children of the circle (Inspect the pen to see):

```
left side
  circle
    right side
```

To make it working, I add the closed tag `</div>` to left, circle, and right sides:
https://codepen.io/phuocng/pen/JjoLqoj?editors=1100

**Comment by hchiam** [comment]
That works. I think the example code needs to be updated. I tested in firefox and chrome with a local file, and still got this: 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18131787/72167035-6291f680-3398-11ea-8452-33d7794da572.png">
I'll make a PR if you'd like.

**Comment by phuoc-ng** [comment]
Fixed.
