### ISSUE TITLE
The site doesn't load

### ISSUE THREAD

**Issue by RinatValiullov** [phuoc-ng/csslayout#123]
**Environment:**

Microsoft Windows 7 Professional SP1
Google Chrome v. 79.0.3945.130

I try to open your [site](https://csslayout.io/) and get an empty page with these errors in console tab:

![err1](https://user-images.githubusercontent.com/9755333/73808382-8e669780-47f1-11ea-9c29-84c263796125.PNG)

![err2](https://user-images.githubusercontent.com/9755333/73808387-93c3e200-47f1-11ea-95ad-8c393bd7c4aa.PNG)

In Network tab:
![net](https://user-images.githubusercontent.com/9755333/73808634-70e5fd80-47f2-11ea-8505-bfe5a5e1f710.PNG)

**Note:**
About 1 second, the site tries to load (for a short time I see the page), but then everything disappears.

**Comment by DanSnow** [comment]
Are you using adblock?

I found a file `https://csslayout.io/patterns-accordion-Cover~patterns-card-Cover~patterns-centering-Cover~patterns-cookie-banner-Cover~p~5fb8d316.js` which will trigger a block rule in the lists 
![image](https://user-images.githubusercontent.com/5575082/73838421-97d21d00-484e-11ea-855a-d86a316f0c8c.png)

I just add a rule to let all the scripts from `csslayout.io` to bypass

```
@@||csslayout.io^$script,1p
```

**Comment by DanSnow** [comment]
@phuoc-ng Maybe configure `output.chunkFilename` in `webpack.config.js` with a name that exclude 
 the `[name]`? e.g. `chunkFilename: 'chunk.[contenthash].js'`

**Comment by RinatValiullov** [comment]
@DanSnow 
Yeah, I use adblock. And think that problem about load the site because of it.  I can't check it out on this machine today, but on similar browser and OS all works now. Tomorrow will test and write about working of the site.

**Comment by phuoc-ng** [comment]
@DanSnow @RinatValiullov 
Thanks for reporting the issue and the suggestion.
I made the PR to fix it [here](https://github.com/phuoc-ng/csslayout/pull/124).

The [website](http://csslayout.io/) is also updated. Can you visit the website to see if it's fixed, @RinatValiullov?

**Comment by DanSnow** [comment]
I can confirm that the website is working after I comment out the custom rule for my adblock

**Comment by RinatValiullov** [comment]
All works now.
Thanks for well-timed support.
