### ISSUE TITLE
Typo in css sample

### ISSUE THREAD

**Issue by malenkiki** [phuoc-ng/csslayout#156]
https://github.com/phuoc-ng/csslayout/blob/5228d1ab54c406fa3c4da44cc34646c91c23674f/client/patterns/split-navigation/Details.tsx#L61

`list-stype-type` must be `list-style-type`.

**Comment by phuoc-ng** [comment]
Can you make a PR to fix it, @malenkiki ?

**Comment by malenkiki** [comment]
Sure.

Done in <https://github.com/phuoc-ng/csslayout/pull/157>

**Comment by phuoc-ng** [comment]
fixed.
