### ISSUE TITLE
Dropdown example is broken

### ISSUE THREAD

**Issue by posobin** [phuoc-ng/csslayout#160]
This is what [this example](https://csslayout.io/patterns/dropdown) looks like in Chrome (Version 88.0.4324.192 (Official Build) (x86_64)), MacOS 11:
![image](https://user-images.githubusercontent.com/741891/108951293-b2cc2680-7635-11eb-8c93-4a7e470963f2.png)

**Comment by phuoc-ng** [comment]
Thanks @posobin 👍 
The issue is [fixed](https://csslayout.io/patterns/dropdown)

<img width="749" alt="Screen Shot 2021-04-02 at 22 15 14" src="https://user-images.githubusercontent.com/57786711/113428402-ed796980-9400-11eb-8af7-4f753f524ae8.png">
